### ISSUE TITLE
avmesos.exception.MesosException: Object of type 'datetime' is not JSON 

### ISSUE THREAD

**Issue by andreaspeters** [AVENTER-UG/python-avmesos#2]
```

Mar 04 18:28:35 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:28:35,466] {mesos_executor.py:219} INFO - Task 1 is in state TASK_STARTING
Mar 04 18:28:36 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:28:36,382] {mesos_executor.py:219} INFO - Task 0 is in state TASK_STARTING
Mar 04 18:28:36 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:28:36,420] {mesos_executor.py:219} INFO - Task 1 is in state TASK_RUNNING
Mar 04 18:28:39 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:28:39,810] {mesos_executor.py:219} INFO - Task 0 is in state TASK_RUNNING
Mar 04 18:29:29 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:29:29,310] {mesos_executor.py:219} INFO - Task 1 is in state TASK_FINISHED
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:29:30,093] {scheduler_job.py:1293} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: Traceback (most recent call last):
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/avmesos/client.py", line 273, in reconcile
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: json.dumps(message),
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: return _default_encoder.encode(obj)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: chunks = self.iterencode(o, _one_shot=True)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: return _iterencode(o, 0)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: o.__class__.__name__)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: TypeError: Object of type 'datetime' is not JSON serializable
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: During handling of the above exception, another exception occurred:
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: Traceback (most recent call last):
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/apache_airflow-2.0.0-py3.6.egg/airflow/jobs/scheduler_job.py", line 1275, in _execute
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: self._run_scheduler_loop()
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/apache_airflow-2.0.0-py3.6.egg/airflow/jobs/scheduler_job.py", line 1379, in _run_scheduler_loop
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: self.executor.heartbeat()
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/apache_airflow-2.0.0-py3.6.egg/airflow/executors/base_executor.py", line 159, in heartbeat
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: self.sync()
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/apache_airflow-2.0.0-py3.6.egg/airflow/executors/mesos_executor.py", line 361, in sync
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: driver.reconcile(key)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: File "/home/airflow/python-airflow/lib/python3.6/site-packages/avmesos/client.py", line 279, in reconcile
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: raise MesosException(e)
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: avmesos.exception.MesosException: Object of type 'datetime' is not JSON serializable
Mar 04 18:29:30 mesos-airflow-ex-0 bash[29582]: [2021-03-04 18:29:30,849] {mesos_executor.py:219} INFO - Task 0 is in state TASK_FINISHED

```

**Comment by andreaspeters** [comment]
Das Problem lag am Mesos_Executor in Airflow. Hier habe ich ein json und nicht nur die TaskID übergeben.
